---
- name: Playbook Sample
  hosts: all
  become: true
  tasks:
  - name: フォルダ(/home/ec2-user/test01)を作成する
    file:
      path: /home/ec2-user/test01
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: "u=rwx,g=rx,o=rx"
      recurse: true
